Add parameters as input
chipsalliance/verible-formatter-action pull request #6
Opened 2022-05-17 07:45 UTC by mole99

This PR adds another input that is used to pass flags to the formatter.

For now, this is still WIP, as some things need to be discussed beforehand:

- It seems that verible's parameter handling has changed. Directories no longer specify all .v and .sv files inside them. Instead, the files have to be passed directly or wildcards can be used e.g.: design/\*/\*/\*.sv but this is only for one hierarchy and not the whole folder.

    > verible-verilog-lint .
    E20220517 09:44:17.093976 17717 verilog_linter.cc:108] Can't read '.': .: is a directory, not a file

Should the README be updated to reflect that? Or should the GitHub action mimic the old behaviour by searching for all .v and .sv files in a directory? Or maybe an issue should be opened on veribles side to allow passing directories again?

- Passing newlines to the inputs fails the action

Currently I specify my parameters like this:

    parameters:
      --indentation_spaces 4
      --module_net_variable_alignment=preserve
      --case_items_alignment=preserve

This works without problems because no newlines are added.

When I use a "|" after "parameters:" newlines will be added after every argument. The GitHub action will see this then as different commands. See [this](https://stackoverflow.com/questions/59954185/github-action-split-long-command-into-multiple-lines/66809682#66809682) stackoverflow answer for more information.

Currently the README also specifies a "|" for the paths. Maybe GitHub changed some behaviour here. Should the README be updated to reflect this?

2022-05-17 15:16 UTC, mglb commented
> This PR adds another input that is used to pass flags to the formatter.
> 
> For now, this is still WIP, as some things need to be discussed beforehand:
> 
>     * It seems that verible's parameter handling has changed. Directories no longer specify all .v and .sv files inside them. Instead, the files have to be passed directly or wildcards can be used e.g.: design/*/*/*.sv but this is only for one hierarchy and not the whole folder.
>       > verible-verilog-lint .
>       > E20220517 09:44:17.093976 17717 verilog_linter.cc:108] Can't read '.': .: is a directory, not a file

I did test it with `verible-v0.0-1213-g9e5c085` (the version used previously by the action) and it fails too. Seems like this action never supported directories.
Which makes sense - picking arbitrary files in a directory tree and overwritting them (due to `--inplace`) doesn't sound good.

> Should the README be updated to reflect that?

Yes.

> Or should the GitHub action mimic the old behaviour by searching for all .v and .sv files in a directory?

I think it would be best to just support `**` (which wildcards any number of subdirectories) in paths. This can be enabled with `shopt -s globstar` in bash.
It would allow path specification to look like `rtl/**/*.{sv,v}`


>     * Passing newlines to the inputs fails the action
> 
> 
> Currently I specify my parameters like this:
> 
> ```
> parameters:
>   --indentation_spaces 4
>   --module_net_variable_alignment=preserve
>   --case_items_alignment=preserve
> ```
> 
> This works without problems because no newlines are added.
> 
> When I use a "|" after "parameters:" newlines will be added after every argument. The GitHub action will see this then as different commands. See [this](https://stackoverflow.com/questions/59954185/github-action-split-long-command-into-multiple-lines/66809682#66809682) stackoverflow answer for more information.
> 
> Currently the README also specifies a "|" for the paths. Maybe GitHub changed some behaviour here. Should the README be updated to reflect this?

Please update the README.

Newline removal would be OK as an extra feature.

2022-05-19 08:36 UTC, mole99 commented
Hi @mglb,

I have added support for the `globstar` option. Also, I included `nullglob` which expands non-matching globs to zero arguments, rather than to themselves.

The `paths` input is now renamed to `files`, since you are actually specifying files.

The README should be updated accordingly. Hopefully I did not miss something.

From my end, this is ready to merge.

2022-05-23 10:14 UTC, mglb requested changes
Just a few requests in the README and description.
The code changes are good.

2022-05-23 10:14 UTC, mglb commented on README.md
> +To search recursively for ``*.v`` and ``*.sv`` files, you can use the ``globstar`` option.
"globstar" is a bash-specific name. People might not understand it, especially without a context.
Maybe something like:

> The patterns are [unix-like globs](https://en.wikipedia.org/wiki/Glob_(programming)#Unix-like) with support for `**` (bash's "globstar").

2022-05-23 10:14 UTC, mglb commented on README.md
> +Additionally, you can add various flags to the formatter with the ``parameter`` input:
`parameters` (with `s`)

2022-05-23 10:14 UTC, mglb commented on action.yml
> +    description: 'Additional parameters to set flags for formatting'
Maybe something like "Additional parameters passed to formatter executable"?

2022-05-25 10:26 UTC, mglb approved these changes
LGTM. Thank you!

2022-05-25 10:33 UTC, tgorochowik approved these changes
Thanks!

2022-05-25 10:33 UTC, merged